spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java-fm-guild
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  batch:
    initialize-schema: always
    job.enabled: false

logging.level.org.springframework.batch.item.support: DEBUG