spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java-fm-guild
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  batch:
    initialize-schema: always
    job:
      enabled: true
      names: fundamentalCsvEtlJob,securitiesCsvEtlJob,pricesCsvEtlJob
  mail:
    host: smtp.gmail.com
    port: 587
#    username: changeme@gmail.com
#    password: changeme
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true


logging.level.org.springframework.batch.item.database.JdbcBatchItemWriter: DEBUG